AllCops:
  TargetRubyVersion: 2.5

Documentation:
  Enabled: false

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

LineLength:
  Max: 160

Metrics/AbcSize:
  Max: 40

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 8

MethodLength:
  Max: 20

StringLiterals:
  EnforcedStyle: double_quotes
