# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "tabular"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Scott Willson"]
  s.date = "2013-05-05"
  s.description = "Tabular is a Ruby library for reading, writing, and manipulating CSV, tab-delimited and Excel data."
  s.email = "scott.willson@gmail.cpm"
  s.extra_rdoc_files = [
    "LICENSE",
    "README"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README",
    "Rakefile",
    "VERSION",
    "lib/tabular.rb",
    "lib/tabular/column.rb",
    "lib/tabular/columns.rb",
    "lib/tabular/keys.rb",
    "lib/tabular/renderer.rb",
    "lib/tabular/row.rb",
    "lib/tabular/support/object.rb",
    "lib/tabular/support/zero.rb",
    "lib/tabular/table.rb",
    "tabular.gemspec",
    "test/column_test.rb",
    "test/columns_test.rb",
    "test/fixtures/blank.txt",
    "test/fixtures/excel.xls",
    "test/fixtures/quoted.txt",
    "test/fixtures/sample.csv",
    "test/fixtures/sample.lif",
    "test/helper.rb",
    "test/row_test.rb",
    "test/table_test.rb",
    "test/zero_test.rb"
  ]
  s.homepage = "http://github.com/scottwillson/tabular"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "Read, write, and manipulate CSV, tab-delimited and Excel data"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ruby-ole>, [">= 0"])
      s.add_runtime_dependency(%q<spreadsheet>, [">= 0"])
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<ruby-ole>, [">= 0"])
      s.add_dependency(%q<spreadsheet>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<ruby-ole>, [">= 0"])
    s.add_dependency(%q<spreadsheet>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

